COM-1653
Mozu/core-theme pull request #201
Opened 2020-05-25 11:43 UTC by sam-ss

disable list control when withlist name get change

2020-05-27 03:50 UTC, Amjcraft submitted a review, later dismissed

2020-05-27 03:53 UTC, Amjcraft requested changes
Since this is on the keyup function can you put a denounce function ( https://underscorejs.org/#debounce) in before executing. 

You know a better approach for this could be to have keyup function just save the list instead. And then add the % if model.isLoading %}disabled="disabled" {% endif %} tag to the remove button like we do with the other buttons. It would also make the above focusout redundant. Thoughts?

2020-05-29 12:09 UTC, sam-ss commented
i have made changes please have a look on it

2020-06-02 14:23 UTC, Amjcraft approved these changes

2020-06-08 17:01 UTC, michaelsadlonkibo commented
This was already merged in commit `1332c3cfdab089bcaa01698518e7caa9e1b34165`.

2020-06-08 17:01 UTC, closed without merging