COM-1937 - Added a new Order Confirmation template as per Opt Out scenario.
Mozu/core-theme pull request #223
Opened 2020-07-29 09:11 UTC by sagarraut0007

…

2020-08-03 05:18 UTC, sagarraut0007 commented
@michaelsadlonkibo , updated this PR

2020-08-10 16:55 UTC, ghost approved these changes
Looks good. The german version is over 160 characters but is not caused by this change.

2020-08-10 20:43 UTC, skrooks requested changes

2020-08-10 20:43 UTC, skrooks commented on templates/mobile-notification/order-confirmation.hypr
> +{{ labels.mobileOrderConfirmationMessage|string_format(model.fulfillmentInfo.fulfillmentContact.firstName, model.fulfillmentInfo.fulfillmentContact.lastNameOrSurname, model.siteId)|safe  }}
According to COM-1937, we need to show the _Retailer Name_, not the shopper's name.

2020-08-16 19:03 UTC, rakesh-dontula approved these changes

2020-08-31 23:01 UTC, merged