COM-1977 : Curbside | Update "LET US KNOW" landing page
Mozu/core-theme pull request #225
Opened 2020-08-05 11:49 UTC by PankajChumbalkarXP

Added new text filed to capture License Plate of customer and its optional field.

2020-08-05 18:54 UTC, ghost requested changes

2020-08-05 18:54 UTC, michaelsadlonkibo commented on labels/de-DE.json
> +  "licensePlateLabel":"Nummernschild # (OPTIONAL)"
This file is sorted alphabetically. Add the new field to the right place. Don't add to the end.

2020-08-05 18:54 UTC, michaelsadlonkibo commented on labels/en-US.json
> +  "licensePlateLabel":"License Plate # (OPTIONAL)"
This file is sorted alphabetically. Add the new field to the right place. Don't add to the end.

2020-08-05 19:01 UTC, michaelsadlonkibo commented
Also the commit message title should not be a copy+paste of the jira issue. Something like this is better:
```
COM-1977 Add license plate field to customer at curbside template

Add a new text field (optional) to capture the License Plate of the customer. The customer at curbside template is used by the customer at curbside "Let Us Know" landing page.
```

2020-08-07 13:42 UTC, Amjcraft approved these changes

2020-08-13 19:09 UTC, ghost approved these changes

2020-08-13 19:10 UTC, merged