COM-2157 Added Storenotification for partialPickup, PickupReady and P…
Mozu/core-theme pull request #247
Opened 2020-09-18 05:36 UTC by hrishid

…ickupReminder

2020-09-18 07:56 UTC, AtulChavan approved these changes

2020-09-22 00:57 UTC, michaelsadlonkibo requested changes

2020-09-22 00:57 UTC, michaelsadlonkibo commented on templates/mobile-notification/pickup-reminder.hypr
> +{% comment %} message length should not exceed 139 characters {% endcomment %}
Should say 160 since 160 is our max message length.

2020-09-22 00:57 UTC, michaelsadlonkibo commented on templates/mobile-notification/ready-for-pickup.hypr
> +{% comment %} message length should not exceed 139 characters {% endcomment %}
Should say 160 since 160 is our max message length.

2020-09-22 00:57 UTC, michaelsadlonkibo commented on theme.json
> +      "title": "Curbside Ready"
Why is the title `Curbside Ready`? Shouldn't it be `Pickup Reminder`?

2020-09-22 00:57 UTC, michaelsadlonkibo commented on theme.json
> +      "title": "Pickup Ready"
Shouldn't the title be `Partial Pickup Ready`?

2020-09-22 00:57 UTC, michaelsadlonkibo commented on labels/de-DE.json
> +  "mobilePickupReminder":"Rappel, les articles de votre commande {0} sont prêts à être ramassés. Vérifiez la commande à {1}",
This file is de-DE which means German. A lot of translations in this file are incorrectly French but they should all be in German.

2020-09-22 00:57 UTC, michaelsadlonkibo commented on labels/en-US.json
> +  "mobileReadyForPickup":"Item(s) in your order {0} is ready for pickup at {1}. Review the order at {2}.",
This text matches the request in the story but there are some minor errors in my opinion. We should confirm the text.

2020-09-22 19:57 UTC, michaelsadlonkibo approved these changes
Changes look good minus the `is` => `are` text. Please make that change then this PR is good to go.

2020-09-22 19:57 UTC, michaelsadlonkibo commented on labels/en-US.json
> +  "mobileReadyForPickup":"Items in your order {0} is ready for pickup at {1}. Review the order at {2}",
`order {0} is ready` should say `order {0} are ready`. Otherwise looks good.
Do the same for both templates. Make sure to update the German, too.

2020-11-10 23:23 UTC, merged