COM-2653:B2B P2 - Email templates for email and print quote
Mozu/core-theme pull request #281
Opened 2021-01-22 14:42 UTC by Rameshdesaiise

Created quote summary template in back-office and emails

2021-01-25 20:31 UTC, srikanthkibo1222 requested changes

2021-01-25 20:31 UTC, srikanthkibo1222 commented on labels/en-US.json
> +  "quoteAdjustments": "Adjustments",
I don't see a quoteAdjustments in de-DE.json

2021-03-01 20:46 UTC, ghost approved these changes

2021-03-22 16:27 UTC, michaelsadlonkibo approved these changes

2021-03-22 16:34 UTC, merged