COM-2889: Added new templates for B2bAccount emails and updated existing
Mozu/core-theme pull request #284
Opened 2021-01-29 11:29 UTC by ysampal

* Added new templates for B2b account created, denied and inactive emails.
* Updated existing email templates for welcome and password reset emails so as to be reused for B2b accounts.

2021-02-01 15:18 UTC, srikanthkibo1222 requested changes

2021-02-01 15:18 UTC, kibo-srikanthbandlamudi commented on labels/en-US.json
> +  "b2bAccountCreatedBlob": "<p>Thanks for creating a B2B account at <a href=\"https://www.kibocommerce.com\">https://www.kibocommerce.com</a> . You account has been submitted for approval.<br/><br/><
Typo - "Your" Account

2021-02-01 15:39 UTC, ysampal commented on labels/en-US.json
> +  "b2bAccountCreatedBlob": "<p>Thanks for creating a B2B account at <a href=\"https://www.kibocommerce.com\">https://www.kibocommerce.com</a> . You account has been submitted for approval.<br/><br/><
Fixed.

2021-02-23 18:03 UTC, srikanthkibo1222 approved these changes

2021-03-22 22:07 UTC, merged