feature/COM-2886
Mozu/core-theme pull request #295
Opened 2021-02-16 15:27 UTC by prakhar308

- Added link in Header to open B2B Account Request form
 - Added validations
 - Added API Integration
 - Displayed success popup message

2021-02-17 06:12 UTC, AtulChavan commented
@Rameshdesaiise I have fixed build issue.
As suggested by @michaelsadlonkibo I have also removed tenant attribute check and made B2B link available to all.

2021-02-17 06:52 UTC, Rameshdesaiise approved these changes

2021-02-22 16:09 UTC, rocky0904 requested changes
change b2b account request to b2b request account everywhere

2021-02-22 17:46 UTC, rocky0904 approved these changes

2021-03-22 17:07 UTC, merged