Feature/COM-3264 Integrated Shipping Method API's
Mozu/core-theme pull request #308
Opened 2021-03-10 14:05 UTC by hrishid

2021-03-10 14:58 UTC, rajeshdatir requested changes

2021-03-10 14:58 UTC, rajeshdatir commented on scripts/modules/b2b-account/edit-quote.js
> +        { var self = this;
add a variable on new line

2021-03-10 14:58 UTC, rajeshdatir commented on scripts/modules/b2b-account/edit-quote.js
> +
Remove blank lines

2021-03-10 14:58 UTC, rajeshdatir commented on scripts/modules/b2b-account/edit-quote.js
> +       {    var self = this;
add curly braces after _function() {_. make it consistent with other functions

2021-03-11 21:44 UTC, rocky0904 requested changes

2021-03-11 21:44 UTC, rocky0904 commented on scripts/modules/b2b-account/edit-quote.js
> +            var json = JSON.parse(JSON.stringify(
indent properly. Use some formatter to format the code properly.

2021-03-23 06:46 UTC, michaelsadlonkibo commented
As part of my rebase I reverted a no-op change to `templates/modules/multi-ship-checkout/shipping-method-item.hypr.live` as it wasn't needed. Cleaned up some whitespace/formatting issues as well. No functional changes.

2021-03-23 06:59 UTC, merged