FFMT-2139 - P and D email templates
Mozu/core-theme pull request #333
Opened 2021-05-03 12:49 UTC by sneha-nerekar

Covered 
1. Expected Delivery Date Update
2. Items Ready for Delivery
 email templates

2021-05-10 22:15 UTC, PapaTaylor commented on labels/en-US.json
> +  "deliveryReadyBody": "Item(s) in your order are ready to be delivery. A member of out team will contact you to schedule the delivery",
Typos. Should be more like this:
"Item(s) in your order are ready to be delivered. A member of our team will contact you to schedule the delivery."

2021-05-10 22:17 UTC, PapaTaylor requested changes
Please see my comment

2021-05-11 04:16 UTC, sneha-nerekar commented
Changed the line as per wireframe "**Item(s) in your order are ready to be delivery.  A member of our team will contact you to schedule the delivery**" also tried to change accordingly in de.json but the line is good there as per google translation, hence no changes required.

2021-05-11 16:05 UTC, PapaTaylor commented on labels/en-US.json
> +  "deliveryReadyBody": "Item(s) in your order are ready to be delivery. A member of our team will contact you to schedule the delivery",
Hi @sneha-nerekar,
There is still an issue with the message; "delivery" in the first sentence should be "delivered".
FROM: "Item(s) in your order are ready to be delivery. A member of our team will contact you to schedule the delivery"
TO: "Item(s) in your order are ready to be deliver**ed**. A member of our team will contact you to schedule the delivery"

2021-05-11 16:06 UTC, PapaTaylor requested changes
Please see my comment.

2021-05-11 16:11 UTC, sneha-nerekar commented on labels/en-US.json
> +  "deliveryReadyBody": "Item(s) in your order are ready to be delivery. A member of our team will contact you to schedule the delivery",
Hi @PapaTaylor, changed the the word, "delivery" to "delivered"

2021-05-11 17:30 UTC, PapaTaylor approved these changes

2021-05-21 20:05 UTC, merged