COM-3641 Replace Submit Changes to Submit Changes & Approve
Mozu/core-theme pull request #342
Opened 2021-05-12 10:23 UTC by SharmaBhushan

2021-05-17 05:13 UTC, sagarraut0007 approved these changes

2021-05-18 12:48 UTC, michaelsadlonkibo requested changes
The label changes do not match the specifics in the story. The text for the existing `approveQuote` and `submitForApproval` labels is fine. You only need to change the labels for `submitChanges`. In this case submit changes is no longer accurate and a new label for `approveQuoteWithChanges` and `submitForApprovalWithChanges` would be best.

Any questions reach out to me.

2021-05-24 17:01 UTC, michaelsadlonkibo commented
Since Bhushan is no longer available to finish this I made some edits to remove unused labels and update the button text based on the latest requirements.

Basically, only the Seller Submit Changes button when a Quote is In Review has been removed and now the Approve Quote button text will dynamically show Approve Quote with Changes based on the draft. No other cases are changed.

2021-05-24 17:01 UTC, michaelsadlonkibo approved these changes

2021-05-27 19:47 UTC, merged