Defect/ffmt 3063: Multiple packing slip not working with Transfer
Mozu/core-theme pull request #392
Opened 2022-02-21 13:20 UTC by kibo-ajayjangam

2022-02-25 21:21 UTC, PapaTaylor commented on templates/back-office/transfer-packing-slip.hypr
> +{% for packages in model.packages %}
Please rename `packages` to its singular form, `package`

e.g.` {% for package in model.packages %}`

2022-02-25 21:29 UTC, PapaTaylor commented on templates/back-office/transfer-packing-slip.hypr
> +                        {% for packagesItemDetails in packages.packingSlipItemDetails %}
Please rename `packagesItemDetails` to be singular and remove trailing `s` from `packages`

e.g. `{% for packageItemDetail in package.packingSlipItemDetails %}`

2022-02-25 21:32 UTC, PapaTaylor commented on templates/back-office/packing-slip-content.hypr
>                          {% for packagesItemDetails in packages.packingSlipItemDetails %}
Please rename `packagesItemDetails` to be singular and remove trailing `s` from `packages`

e.g. `{% for packageItemDetail in package.packingSlipItemDetails %}`

2022-02-25 21:34 UTC, PapaTaylor commented on templates/back-office/packing-slip-content.hypr
> +                                {% if packagesItemDetails.lineId == item.lineId %}
Change to `{% if packageItemDetail.lineId == item.lineId %}`

2022-02-25 21:36 UTC, PapaTaylor commented on templates/back-office/transfer-packing-slip.hypr
> +                                {% if packagesItemDetails.lineId == item.lineId %}
Change to `{% if packageItemDetail.lineId == item.lineId %}`

2022-02-25 21:36 UTC, PapaTaylor commented on templates/back-office/transfer-packing-slip.hypr
> +                                        {{ packagesItemDetails.quantity }}
Change to `{% if packageItemDetail.quantity %}`

2022-02-25 21:38 UTC, PapaTaylor requested changes
Looks good but please address requested changes.

2022-03-01 17:06 UTC, kibo-kellytaylor approved these changes
Looks good!

2022-03-01 17:07 UTC, PapaTaylor approved these changes
Looks good!

2022-03-08 23:26 UTC, merged