COM-5525 : B2B NonPurchaser can initiate Quotes
Mozu/core-theme pull request #419
Opened 2022-06-06 16:02 UTC by kibo-pawanjadhav

2022-06-06 16:14 UTC, kibo-raghu requested changes

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/b2b-account/quotes.js
> +            var isNonPurchaserUser=  !require.mozuData('user').behaviors.includes(1000) && !require.mozuData('user').behaviors.includes(1005);
Add space before `=`

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/b2b-account/quotes.js
> +                    collection.attributes.rowActions=[];
Add space before and after `=`

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/b2b-account/quotes.js
> +                console.log(collection);
Remove Console.Log everywhere

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/b2b-account/quotes.js
> +        rowActions:
Revert changes if nothing is added

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/b2b-account/view-quote.js
> +            console.log(self.model.get("isNonPurchaserUser"));
Remove console.log

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/b2b-account/view-quote.js
> +            var isNonPurchaserUser=  !require.mozuData('user').behaviors.includes(1000) && !require.mozuData('user').behaviors.includes(1005);
Add spaces before after `=` everywhere

2022-06-06 16:14 UTC, kibo-raghu commented on scripts/modules/cart-common-view.js
> +          console.log( require.mozuData('user'));
remove console.log

2022-06-07 07:01 UTC, Kibo-Sagar approved these changes
changes looks good to me.

2022-06-21 15:55 UTC, kibo-raghu approved these changes

2022-06-21 15:56 UTC, merged