FFMT-3476 - Packing slip and Email changes
Mozu/core-theme pull request #440
Opened 2022-12-19 14:07 UTC by kibo-snehanerekar

Email template changes below -
item cancel - done
return authorized - done
return request reject - done
return item received - done
return has been updated  - Done
shipment-confirmation.hypr - done
order-cancel.hypr - done
order-pickup-ready.hypr - done 
order-pickup-reminder.hypr -done
order-shipped.hypr - done
partial-pickup-ready.hypr - done
transfer-shipment-created-fulfiller.hypr - done
transfer-shipment-created.hypr - done
transfer-shipment-shipped.hypr - done

Added Packing slip changes

2022-12-20 20:16 UTC, kibo-kellytaylor commented on templates/email/order-cancel.hypr
> +                {% if ((not item.originalLineId) && model.substitutedItems.length > 0) %}
@kibo-snehanerekar I see the following conditional statement across most of the templates in your PR and I'm wondering if the check should include an OR for cases where there are no substitutions on the shipment. For example, OR `(not model.substitutedItems.length > 0)` ...maybe I'm reading it wrong.
```
{% if ((not item.originalLineId) && model.substitutedItems.length > 0) %}
```

2022-12-20 20:20 UTC, kibo-kellytaylor reviewed
@kibo-snehanerekar I see the following conditional statement across the templates in your PR and I'm wondering if the check should include an OR for cases where there are no substitutions on the shipment. 

For example, OR `((not model.substitutedItems)` OR `(not model.substitutedItems.length > 0))` ...maybe I'm reading it wrong.
```
{% if ((not item.originalLineId) && model.substitutedItems.length > 0) %}
```

cc: @Kibo-Omkar

2022-12-21 08:07 UTC, kibo-snehanerekar commented
> 

@kibo-kellytaylor Per discussion with @Kibo-Omkar we no longer required a second condition. The first condition will suffice the requirement to view only Original items hence removing the second condition.

2022-12-21 14:58 UTC, Kibo-Omkar requested changes
Hi @kibo-snehanerekar ,
As discussed, kindly address the changes.

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/back-office/packing-slip-content.hypr
> +                {% if model.substitutedItems.length > 0 %}
` {% if model.substitutedItems.length > 0 && item.originalLineId %}`

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/back-office/packing-slip-content.hypr
> +                                {% if substitutedItem.originalLineId && substitutedItem.length > 0 %}
Can we rename the substitute item and substituted Item (Or Original Items here)?
So that we can easily identify the table grids?
For example 
`{% if substitutedItem.originalLineId && substitutedItems.length > 0 %}`

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/back-office/packing-slip-content.hypr
> +                            {% for substitutedItem in model.items %}
As we are showing substitute items, so can we rename the variable accordingly?
` for substituteItem in model.items`

**SubstituteItem** --> _Items are selected as substitutes for an item._
**SubstitutedItem** --> _Items that are substituted with other items._

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/email/item-cancel.hypr
> +            {% if model.substitutedItems.length > 0 %}
Please check the naming convention while iterating on items.
SubstituteItem --> Items are selected as substitutes for an item.
SubstitutedItem --> Items that are substituted with other items.

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/email/order-cancel.hypr
> +                    {% for substitutedItem in model.items %}
Please check the naming convention while iterating on items.
SubstituteItem --> Items are selected as substitutes for an item.
SubstitutedItem --> Items that are substituted with other items.

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/email/order-pickup-ready.hypr
> +                    <tr class="mz-ordersummary-line mz-ordersummary-line-item">
Can we combine both if statements?
` {% if (not item.originalLineId) &&  (item.quantity > 0) %}`

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/email/order-pickup-ready.hypr
> +                {% for substitutedItem in model.items %}
Please check the comment regarding the naming convention.

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/email/order-pickup-reminder.hypr
> +                    {% if substitutedItem.originalLineId && substitutedItem.length > 0 %}
On line 241, we are iterating on  model.items and using "substitutedItem" as a variable (Iterator variable) to access the values from  "the model.items"
On line 242 we are  "substitutedItem.length".
It seems you are checking the "length" property inside the "item" model.

2022-12-21 14:58 UTC, Kibo-Omkar commented on templates/email/order-shipped.hypr
> +                {% if (packageItem.quantity > 0) %}
Please check the above comment regarding the "originalLineId"

2022-12-22 15:43 UTC, kibo-snehanerekar commented on templates/back-office/packing-slip-content.hypr
> +                                {% if substitutedItem.originalLineId && substitutedItem.length > 0 %}
I tried it earlier but sometimes it doesn't work in hypr for some reason hence added seperately

2022-12-22 15:43 UTC, kibo-snehanerekar commented on templates/email/item-cancel.hypr
> +            {% if model.substitutedItems.length > 0 %}
Changed the naming convention for SubstituteItem

2022-12-22 15:43 UTC, kibo-snehanerekar commented on templates/email/order-pickup-reminder.hypr
> +                    {% if substitutedItem.originalLineId && substitutedItem.length > 0 %}
changed it to quantity

2022-12-22 15:51 UTC, kibo-snehanerekar commented
Done with the changes required, except one of adding if condition in one line since I found it breaking at some point

2022-12-22 16:38 UTC, Kibo-Omkar approved these changes
Hi @kibo-snehanerekar ,  It seems there are a few comments that need to be addressed and I am also having a few questions related to that but by considering the priority of the ticket and as per your comment (https://kibo.atlassian.net/browse/FFMT-3476?focusedCommentId=456447)  I have approved the same.
cc: @kibo-kellytaylor 
Thank you.

2022-12-22 16:38 UTC, Kibo-Omkar commented on templates/email/order-pickup-ready.hypr
> +    {% if model.substitutedItems.length > 0 %}
It's been a good practice to check the object before accessing its properties.
`{% if model.substitutedItems && model.substitutedItems.length > 0 %}`

2022-12-22 20:18 UTC, kibo-kellytaylor approved these changes

2022-12-22 20:19 UTC, merged