FFMT-3648 - new field Product Name in return receipt pdf
Mozu/core-theme pull request #454
Opened 2023-03-06 15:15 UTC by kibo-snehanerekar

Added new field Product Name in return receipt pdf under substitute section, also changed some verbiage according to the screenshots of this ticket

2023-03-08 05:37 UTC, kibo-kellytaylor commented on labels/de-DE.json
> +  "returnReceiptsubstitutedQty":"Ersatzmenge",
These should be all camel-case...
```
  "returnReceiptSubstitutedQty":"Ersatzmenge",
  "returnReceiptSubstitutedProductName":"Produktname"

2023-03-08 05:40 UTC, kibo-kellytaylor commented on labels/en-US.json
> +  "returnReceiptsubstitutedQty":"Substitute Qty",
fix camel-casing
```
  "returnReceiptSubstitutedQty":"Substitute Qty",
  "returnReceiptSubstitutedProductName":"Product Name",

2023-03-08 05:41 UTC, kibo-kellytaylor commented on templates/back-office/return-receipt-content.hypr
> +                <th class="break-word">{{ labels.returnReceiptsubstitutedProductName }}</th>
fix camel-casing

2023-03-08 05:42 UTC, kibo-kellytaylor requested changes
Please address review comments. Thanks

2023-03-08 08:08 UTC, Kibo-Omkar requested changes
@kibo-snehanerekar Kindly let me know about the below queries.

2023-03-08 08:08 UTC, Kibo-Omkar commented on templates/back-office/return-receipt-content.hypr
> +                <td class="align-right top-border" colspan="6">
Will colspan value be affected if there will be no more substitute items?

2023-03-08 08:49 UTC, kibo-snehanerekar commented on labels/de-DE.json
> +  "returnReceiptsubstitutedQty":"Ersatzmenge",
Fixed

2023-03-08 08:49 UTC, kibo-snehanerekar commented on labels/en-US.json
> +  "returnReceiptsubstitutedQty":"Substitute Qty",
Fixed

2023-03-08 08:49 UTC, kibo-snehanerekar commented on templates/back-office/return-receipt-content.hypr
> +                <th class="break-word">{{ labels.returnReceiptsubstitutedProductName }}</th>
Fixed

2023-03-08 08:49 UTC, kibo-snehanerekar commented on templates/back-office/return-receipt-content.hypr
> +                <td class="align-right top-border" colspan="6">
No, it will not be affected, since there is a different footer for each table(original item table and substitute item table) and it is visible according to the substitution condition

2023-03-08 12:19 UTC, Kibo-Omkar approved these changes
Approved.

2023-03-09 15:25 UTC, kibo-kellytaylor approved these changes

2023-03-09 15:40 UTC, merged